export const Types = {
  //Sponsors
  SET_SPONSORS: 'SET_SPONSORS',
  SET_FILTERED_SPONSORS: 'SET_FILTERED_SPONSORS',
  CLEAR_SPONSORS: 'CLEAR_SPONSORS',
  CLEAR_FILTERED_SPONSORS: 'CLEAR_FILTERED_SPONSORS'
};
